package com.crgt.router;

/**
 * compiler constants
 *
 * @author android
 * @date 2019/6/5
 * @mail android@crgecent.com
 */

public class CompilerConsts {

    // Generate
    // TODO: 2019/6/5 can be config in build.gradle
    public static final String OUTPUT_DIRECTORY = "com.crgt.router";

    public static final String ROUTER_ROSTER_NAME = "Roster";

    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY ROUTER PROCESSOR.";

    public static final String METHOD_GET_ACTIVITIES = "getActivities";

    public static final String METHOD_GET_FRAGMENTS = "getFragments";

    public static final String METHOD_GET_SERVICES = "getServices";

    public static final String METHOD_PARAM_NAME = "rosterMap";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";

    public static final String FRAGMENT = "android.app.Fragment";

    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";

    public static final String SERVICE = "com.crgt.router.autofillparam.IParamProvider";
}
